const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "+94765665354"
const SESSION_ID = "PRABATH-MD~QPk0hKQA#ol0XVuezp4wK3zUAe-POeEONYt4NktUe34aLo_P1AJE"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
