const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "+94765665354"
const SESSION_ID = "PRABATH-MD~dr8TzDJY#cdPV5iJy_HBOUgS3k1XQ0ObX7JxaA71imdUHbCVdE0s"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
